version: "3.8"

services:

  auth-service:
    build: ./services/auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/auth-service/:/app/
    ports:
      - 8005:8000
    env_file:
      - .env
    depends_on:
      - users-service
    networks:
      - network

  users-service:
    build: ./services/users-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/users-service/:/app/
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - users-database
    networks:
      - network

  warehouse-service:
    build: ./services/warehouse-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/warehouse-service/:/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - warehouse-database
    networks:
      - network

  orders-service:
    build: ./services/orders-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/orders-service/:/app/
    ports:
      - 8003:8000
    env_file:
      - .env
    depends_on:
      - orders-database
    networks:
      - network

  analytics-service:
    build: ./services/analytics-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/analytics-service/:/app/
    ports:
      - 8004:8000
    env_file:
      - .env
    depends_on:
      - analytics-database
    networks:
      - network

  users-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_DB}
    ports:
      - "5433:5432"
    volumes:
      - users_pgdata:/var/lib/postgresql/data
    networks:
      - network

  warehouse-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB}
    ports:
      - "5434:5432"
    volumes:
      - warehouse_pgdata:/var/lib/postgresql/data
    networks:
      - network

  orders-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDERS_DB}
    ports:
      - "5435:5432"
    volumes:
      - orders_pgdata:/var/lib/postgresql/data
    networks:
      - network

  analytics-database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ANALYTICS_DB}
    ports:
      - "5436:5432"
    volumes:
      - analytics_pgdata:/var/lib/postgresql/data
    networks:
      - network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users-service
      - warehouse-service
      - orders-service
      - analytics-service
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  users_pgdata:
  warehouse_pgdata:
  orders_pgdata:
  analytics_pgdata: